<!DOCTYPE html><html lang="es" data-bs-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Descubre los fundamentos de excepciones en Python: gestión de errores desde el punto de vista de Programación Orientada a Objetos para código robusto."><meta name="tittle" content="POO: Excepciones Python 3 - Ing. Eduardo Herrera Forero."><meta name="author" content="Ing. Eduardo Herrera Forero"><meta name="application-name" content="EHF"><meta name="robots" content="index, follow"><link rel="canonical" href="https://eduardoherreraf.github.io/cursoPython3-0706_poo_excepciones.html"><meta property="og:type" content="website"><meta property="og:title" content="POO: Excepciones Python 3 - Ing. Eduardo Herrera Forero."><meta property="og:description" content="Descubre los fundamentos de excepciones en Python: gestión de errores desde el punto de vista de Programación Orientada a Objetos para código robusto."><meta property="og:image" content="https://i.imgur.com/JKbKYrO.png"><meta property="og:image:alt" content="Logo del ingeniero Eduardo Herrera Forero"><meta property="og:url" content="https://eduardoherreraf.github.io/cursoPython3-0706_poo_excepciones.html"><meta property="og:locale" content="es_CO"><meta name="twitter:card" content="content" ="summary"><meta name="twitter:title" content="POO: Excepciones Python 3 - Ing. Eduardo Herrera Forero."><meta name="twitter:description" content="Descubre los fundamentos de excepciones en Python: gestión de errores desde el punto de vista de Programación Orientada a Objetos para código robusto."><meta name="twitter:image" content="https://i.imgur.com/JKbKYrO.png"><meta name="twitter:image:alt" content="Logo del ingeniero Eduardo Herrera Forero"><meta name="twitter:url" content="https://eduardoherreraf.github.io/cursoPython3-0706_poo_excepciones.html"><meta name="twitter:site" content="@ehfeduardo"><link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.d2cbc014.png"><link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.02c0440e.png"><link rel="icon" type="image/png" sizes="192x192" href="android-chrome-192x192.9d63268f.png"><link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.a17b4569.png"><link rel="manifest" href="site.webmanifest"><link rel="mask-icon" href="safari-pinned-tab.cd218f89.svg" color="#5bbad5"><meta name="msapplication-TileColor" content="#da532c"><meta name="theme-color" content="#ffffff"><title>POO: Excepciones Python 3 - Ing. Eduardo Herrera Forero.</title><link rel="stylesheet" href="index.f6012c1f.css"><script type="module" defer src="index.d07dbcde.js"></script><meta name="google-site-verification" content="2H5ZMCD1_xl7oxaiqnopfdQBnIXVIOfmW0UBSa5sQJc"></head><body>  <nav class="border border-1 fixed-top nav-underline navbar navbar-expand-lg"> <div class="container-fluid">  <a class="align-items-center d-flex ms-2 navbar-brand text-decoration-none" href="index.html"> <img src="logo.f31ffce0.png" alt="Logo de Ing. Eduardo Herrera Forero" width="30" height="30" class="align-text-top d-inline-block me-1"> <span class="d-lg-inline d-none">Ing. Eduardo Herrera Forero</span> </a>  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>  <div class="collapse ms-auto navbar-collapse text-center" id="navbarSupportedContent"> <ul class="justify-content-lg-end mb-2 mb-lg-0 ms-auto navbar-nav w-100"> <li class="nav-item"> <a class="mx-1 nav-link text-decoration-none" href="index.html">SOBRE MÍ</a> </li> <li class="nav-item"> <a class="mx-1 nav-link text-decoration-none" href="index.html#resume">EXPERIENCIA</a> </li> <li class="nav-item"> <a class="mx-1 nav-link text-decoration-none" href="index.html#portfolio">PORTAFOLIO</a> </li> <li class="nav-item"> <a class="mx-1 nav-link text-decoration-none" href="index.html#studies">ESTUDIOS</a> </li> <li class="nav-item"> <a class="active mx-1 nav-link text-decoration-none" href="index.html#blog">PUBLICACIONES</a> </li> <li class="nav-item"> <a class="mx-1 nav-link text-decoration-none" href="index.html#contact">CONTACTO</a> </li> </ul> </div> </div> </nav>   <div class="col mx-1 row"> <main class="col-lg-9 pt-5"> <section class="pb-3">  <article class="border-1 border-bottom pb-3 row" data-bs-spy="scroll" data-bs-target="#list-example" data-bs-smooth-scroll="true"> <div> <header> <h1>POO: Excepciones en Python</h1> </header> <div class="mt-5"> <p> Las excepciones en Python son un mecanismo para manejar errores y otros eventos inesperados que pueden ocurrir durante la ejecución de un programa. En la programación orientada a objetos (POO), las excepciones permiten que los objetos manejen errores de manera más estructurada y controlada </p> <div class="imagen text-center"> <figure> <img src="https://i.ibb.co/1f9pbDg/poexcepciones.jpg" class="img-fluid rounded-4" width="80%" alt="POO: Excepciones en Python  " title="¿Cómo manejar una excepción en Python?"> <figcaption>POO: Excepciones en Python</figcaption> </figure> </div> </div>  <div id="teoriaBasicaDeExcepcionesClasicas" class="mt-5"> <h2 class="mt-1">Teoría Básica de Excepciones Clásicas</h2> <p> Una excepción es un evento que interrumpe el flujo normal de un programa. Esto puede ocurrir debido a errores como: </p> <ul> <li>Intentar dividir entre cero.</li> <li>Acceder a un índice fuera de rango en una lista.</li> <li>Operar sobre un archivo que no existe.</li> </ul> <p> En Python, las excepciones son objetos derivados de la clase base <code>BaseException</code>, lo que refuerza su integración con la POO. </p> <p> Las excepciones pueden ser manejadas utilizando bloques <code>try</code>, <code>except</code>, <code>else</code> y <code>finally</code>. A continuación, se explica cada uno de estos bloques con un ejemplo: </p> <ul> <li> <span class="fw-bold"><code>try</code></span>: Este bloque contiene el código que puede generar una excepción. </li> <li> <span class="fw-bold"><code>except</code></span>: Este bloque maneja la excepción que se genera en el bloque <code>try</code>. Puedes tener múltiples bloques <code>except</code> para manejar diferentes tipos de excepciones. </li> <li> <span class="fw-bold"><code>else</code></span>: Este bloque se ejecuta si no se genera ninguna excepción en el bloque <code>try</code>. </li> <li> <span class="fw-bold"><code>finally</code></span>: Este bloque se ejecuta siempre, independientemente de si se generó una excepción o no. </li> </ul> <p>Ejemplo que ilustra el uso de estos bloques:</p> <pre class="line-numbers" data-src-status="loaded" tabindex="0">
                <code class="language-python" data-prismjs-copy="Copy">
                  def dividir_numeros(a, b):
                      try:
                          # Intentamos dividir a entre b
                          resultado = a / b
                      except ZeroDivisionError as e:
                          # Manejamos la excepción de división por cero
                          print(f"Error: {e}")
                          return None
                      except TypeError as e:
                          # Manejamos la excepción de tipo incorrecto
                          print(f"Error: {e}")
                          return None
                      else:
                          # Este bloque se ejecuta si no hay excepciones
                          print("La división se realizó con éxito.")
                          return resultado
                      finally:
                          # Este bloque se ejecuta siempre
                          print("Ejecución del bloque finally.")
                  # Ejemplos de uso
                  print(dividir_numeros(10, 2))    # Debería imprimir "La división se realizó con éxito." y luego "Ejecución del bloque finally."
                  print(dividir_numeros(10, 0))    # Debería imprimir "Error: division by zero" y luego "Ejecución del bloque finally."
                  print(dividir_numeros(10, 'a'))  # Debería imprimir "Error: unsupported operand type(s) for /: 'int' and 'str'" y luego "Ejecución del bloque finally."
                </code>
            </pre> </div>   <div id="lasExcepcionesSonClases" class="mt-5"> <h2 class="mt-1">Las Excepciones Son Clases</h2>  <div> <h3>Jerarquía de Excepciones</h3> <p> Las excepciones en Python son implementadas como clases, y todas las excepciones derivan de la clase base <code>BaseException</code>. La mayoría de las excepciones que se encuentran en el uso diario derivan de la clase <code>Exception</code>, que a su vez es una subclase de <code>BaseException</code>. </p> <p>Aquí hay una vista general de la jerarquía de excepciones en Python:</p> <pre class="line-numbers" data-src-status="loaded" tabindex="0">
                  <code class="language-plaintext" data-prismjs-copy="Copy">
                    BaseException
                    ├── Exception
                    │    ├── ArithmeticError
                    │    │    ├── FloatingPointError
                    │    │    ├── OverflowError
                    │    │    └── ZeroDivisionError
                    │    ├── AssertionError
                    │    ├── AttributeError
                    │    ├── BufferError
                    │    ├── EOFError
                    │    ├── ImportError
                    │    │    └── ModuleNotFoundError
                    │    ├── LookupError
                    │    │    ├── IndexError
                    │    │    └── KeyError
                    │    ├── MemoryError
                    │    ├── NameError
                    │    │    └── UnboundLocalError
                    │    ├── OSError
                    │    │    ├── BlockingIOError
                    │    │    ├── ChildProcessError
                    │    │    ├── ConnectionError
                    │    │    │    ├── BrokenPipeError
                    │    │    │    ├── ConnectionAbortedError
                    │    │    │    ├── ConnectionRefusedError
                    │    │    │    └── ConnectionResetError
                    │    │    ├── FileExistsError
                    │    │    ├── FileNotFoundError
                    │    │    ├── IsADirectoryError
                    │    │    ├── NotADirectoryError
                    │    │    ├── InterruptedError
                    │    │    ├── PermissionError
                    │    │    ├── ProcessLookupError
                    │    │    └── TimeoutError
                    │    ├── ReferenceError
                    │    ├── RuntimeError
                    │    │    ├── NotImplementedError
                    │    │    └── RecursionError
                    │    ├── StopIteration
                    │    ├── StopAsyncIteration
                    │    ├── SyntaxError
                    │    │    └── IndentationError
                    │    │         └── TabError
                    │    ├── SystemError
                    │    ├── TypeError
                    │    ├── ValueError
                    │    │    └── UnicodeError
                    │    │         ├── UnicodeDecodeError
                    │    │         ├── UnicodeEncodeError
                    │    │         └── UnicodeTranslateError
                    │    └── Warning
                    │         └── DeprecationWarning
                    │         └── PendingDeprecationWarning
                    │         └── RuntimeWarning
                    │         └── SyntaxWarning
                    │         └── UserWarning
                    │         └── FutureWarning
                    │         └── ImportWarning
                    │         └── UnicodeWarning
                    │         └── BytesWarning
                    │         └── ResourceWarning
                    ├── GeneratorExit
                    ├── KeyboardInterrupt
                    ├── SystemExit
                  </code>
              </pre> </div>   <div> <h3>Acceso a Atributos en Excepciones</h3> <p> En Python, la palabra clave <code>as</code> se utiliza en el contexto de manejo de excepciones para asignar una excepción capturada a una variable. Esto permite acceder a la información de la excepción, como su mensaje de error y otros atributos, dentro del bloque <code>except</code>. </p> <p>Sintaxis Básica:</p> <pre class="line-numbers" data-src-status="loaded" tabindex="0">
                  <code class="language-python" data-prismjs-copy="Copy">
                    try:
                        # Código que puede generar una excepción
                    except ExceptionType as variable:
                        # Manejo de la excepción utilizando la variable
                  </code>
              </pre> <p>Ejemplo básico:</p> <pre class="line-numbers" data-src-status="loaded" tabindex="0">
                  <code class="language-python" data-prismjs-copy="Copy">
                    try:
                        resultado = 10 / 0  # Esto genera un ZeroDivisionError
                    except ZeroDivisionError as e:
                        print(f"Ha ocurrido un error: {e}")
                    # Salida: Ha ocurrido un error: division by zero
                  </code>
                </pre> <p>Desglose del código:</p> <ul> <li> <span class="fw-bold"><code>try</code></span>: Se intenta ejecutar el código que podría generar un error. </li> <li> <span class="fw-bold"><code>except ZeroDivisionError as e</code></span>: <ul> <li> Captura la excepción del tipo <code>ZeroDivisionError</code>. </li> <li>Asigna la instancia de la excepción capturada a la variable <code>e</code>.</li> </ul> </li> <li> <span class="fw-bold"><code>e</code></span>: Es una instancia de <code>ZeroDivisionError</code> y contiene información adicional sobre el error, como el mensaje de error. </li> </ul> </div>   <div> <h3>Acceso a Otros Atributos de la Excepción</h3> <p> Algunas excepciones tienen atributos adicionales que puedes acceder. Por ejemplo, la excepción <code>OSError</code> tiene un atributo <code>errno</code> que contiene el número de error del sistema operativo: </p> <pre class="line-numbers" data-src-status="loaded" tabindex="0">
                  <code class="language-python" data-prismjs-copy="Copy">
                    try:
                        with open('archivo_inexistente.txt', 'r') as file:
                            contenido = file.read()
                    except FileNotFoundError as e:
                        print(f"Error al abrir el archivo: {e}")
                        print(f"Número de error: {e.errno}")
                  </code>
                </pre> </div>  </div>   <div id="comoCrearUnaExcepcionPropia" class="mt-5"> <h2 class="mt-1">Cómo Crear una Excepción Propia</h2> <p> Para crear una excepción propia en Python, se debe definir una nueva clase que herede de la clase base <code>Exception</code>. Esta clase personalizada puede incluir métodos y atributos adicionales según sea necesario. A continuación, se presenta un ejemplo de cómo redactar una excepción propia en tercera persona. </p> <p> Primero, se define la clase de la excepción personalizada. En este ejemplo, se creará una excepción llamada <code>MiExcepcionPersonalizada</code>: </p> <pre class="line-numbers" data-src-status="loaded" tabindex="0">
                <code class="language-python" data-prismjs-copy="Copy">
                  # Definición de la excepción personalizada
                  class MiExcepcionPersonalizada(Exception):
                      """
                      Esta clase representa una excepción personalizada que se puede lanzar
                      cuando ocurre un error específico en el programa.
                      """
                      def __init__(self, mensaje):
                          """
                          Inicializa la excepción con un mensaje descriptivo del error.
                          :param mensaje: Un mensaje descriptivo del error.
                          """
                          super().__init__(mensaje)
                  # Función que puede lanzar la excepción personalizada
                  def funcion_que_puede_fallar(condicion):
                      """
                      Esta función lanza una excepción personalizada si se cumple una condición específica.
                      :param condicion: Una condición booleana que determina si se lanza la excepción.
                      :raises MiExcepcionPersonalizada: Si la condición es verdadera.
                      """
                      if condicion:
                          raise MiExcepcionPersonalizada("Ha ocurrido un error específico.")
                  # Uso de la excepción personalizada en un bloque try-except
                  try:
                      funcion_que_puede_fallar(True)
                  except MiExcepcionPersonalizada as e:
                      print(f"Se ha capturado una excepción: {e}")
                </code>
              </pre> <p>En este ejemplo:</p> <ul> <li> <span class="fw-bold">Definición de la Excepción Personalizada</span>: <ul> <li> Se define una clase <code>MiExcepcionPersonalizada</code> que hereda de Exception. </li> <li> El método <code>__init__</code> se utiliza para inicializar la excepción con un mensaje descriptivo. </li> </ul> </li> <li> <span class="fw-bold">Función que Puede Fallar</span>: <ul> <li> Se define una función <code>funcion_que_puede_fallar</code> que toma una condición booleana como argumento. </li> <li> Si la condición es verdadera, la función lanza la excepción personalizada con un mensaje específico. </li> </ul> </li> <li> <span class="fw-bold">Uso de la Excepción Personalizada</span>: <ul> <li> Se utiliza un bloque <code>try</code>-except para llamar a la función <code>funcion_que_puede_fallar</code> con una condición verdadera. </li> <li> Si la excepción personalizada es lanzada, se captura y se imprime un mensaje indicando que se ha capturado la excepción. </li> </ul> </li> </ul> </div>  </div> </article>   <article class="pt-5 row" id="comment"> <br> <h2>COMENTARIOS</h2> <p> Si tiene alguna inquietud, duda o ha encontrado algún error, por favor infórmelo a través del formulario disponible para este propósito. </p> <div class="d-flex justify-content-center"> <form action="https://formsubmit.co/herreraforeroeduardo@gmail.com" method="post" id="myForm"> <div class="d-flex flex-column input-group justify-content-center"> <label for="name" class="pe-2">Nombre:</label> <input type="text" name="name" id="name" placeholder="Eduardo Herrera Forero" class="rounded" required> <label for="email" class="pe-2">Email:</label> <input type="email" name="email" id="email" placeholder="herreraforeroeduardo@gmail.com" class="rounded" required> <label for="message" class="pe-2">Mensaje:</label> <textarea name="message" id="message" cols="30" rows="5" placeholder="Su comentario..." class="rounded rounded-3"></textarea> <input class="border border-2 btn btn-outline-light my-3 rounded-pill" type="submit" value="Enviar..."> </div> <p> La política de privacidad, y los términos y condiciones están disponibles en el formulario de contacto. </p> </form> </div> </article>  </section> </main>   <aside class="col-lg-3 d-lg-block d-none pt-5"> <h2 class="h3">En Este Artículo</h2> <ul class="list-group"> <li class="list-group-item"> <a href="#teoriaBasicaDeExcepcionesClasicas">Teoría Básica de Excepciones Clásicas</a> </li> <li class="list-group-item"> <a href="#lasExcepcionesSonClases">Las Excepciones Son Clases</a> </li> <li class="list-group-item"> <a href="#comoCrearUnaExcepcionPropia">Cómo Crear una Excepción Propia</a> </li> </ul> </aside>  </div>   <button onclick="topFunction()" id="myBtnScroll" title="Go to top"> <svg width="32" height="32" fill="currentColor" class="bi bi-arrow-bar-up" style="margin-left:-2px" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M8 10a.5.5 0 0 0 .5-.5V3.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 3.707V9.5a.5.5 0 0 0 .5.5m-7 2.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1-.5-.5"/></svg> </button>  </body></html>